### PR TITLE
Change arity of function aec_tx:new/2 -> aec_tx:new/1

### PR DESCRIPTION
**Pull request by zp-sd**
Relates to https://github.com/aeternity/epoch/pull/322.

### CODE REVIEW

**Comment by uwiger** [comment]
What is the rationale?

**Comment by lucafavatella** [comment]
Rationale is that state trees were not used in creation of transaction hence was removed from parameters - hence the arity change.
https://github.com/aeternity/epoch/pull/322/files#diff-a0ec65d06094571b3bc26db62c3c54bcR15

**Comment by lucafavatella** [comment]
This PR cannot be merged yet though, as epoch master depends (at the moment) on master of this repo.
https://github.com/aeternity/epoch/blob/3ddf1b87250adc5e64289d7d5cd7b4b25fa94335/rebar.config#L29

**Comment by zp-sd** [comment]
Yes, I think I should tag current master first to not break current `epoch` master.

**Comment by zp-sd** [comment]
@uwiger This is the removal of parameter not used in creation of transaction, suggested by @happi (so basically API cleanup). But this cannot be merged before https://github.com/aeternity/epoch/pull/325 goes in.

**Review by lucafavatella — APPROVED** [review]
"this cannot be merged before aeternity/epoch#325 goes in."

**Review by uwiger — APPROVED** [review]

**Pull request merged**
